/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckIndexRouteImport } from './routes/deck/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck/$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIndexRoute = DeckIndexRouteImport.update({
  id: '/deck/',
  path: '/deck/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deck': typeof DeckIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deck': typeof DeckIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/deck/': typeof DeckIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$deckId' | '/deck'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$deckId' | '/deck'
  id: '__root__' | '/' | '/deck/$deckId' | '/deck/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  DeckIndexRoute: typeof DeckIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/': {
      id: '/deck/'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  DeckIndexRoute: DeckIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
